AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS WAF"

Parameters:
  AllowIP:
    Type: String
    Default: "14.10.58.192/32"
    Description: "Allow IP"

  SPAIPSetRule:
    Type: String
    Default: "SPAIPRule"
    Description: "Rule Name"

Resources:
  SPAWAFIPSet:
    Type: "AWS::WAF::IPSet"
    Properties: 
      Name: "IPSet for blacklisted IP adresses"
      IPSetDescriptors: 
        - 
          Type: "IPV4"
          Value: !Ref AllowIP
        - 
          Type: "IPV4"
          Value: "192.0.7.0/24"
  SPARule:
    Type: "AWS::WAF::Rule"
    Properties: 
      MetricName: !Ref SPAIPSetRule
      Name: !Ref SPAIPSetRule
      Predicates:
      - 
        DataId:
          Ref: "SPAWAFIPSet"
        Negated: false
        Type: "IPMatch"

  SPAWebACL: 
    Type: "AWS::WAF::WebACL"
    Properties: 
      Name: "WebACL for SPA"
      DefaultAction:
        # BLOCK or ALLOW or COUNT
        Type: "BLOCK"
      MetricName: "SPAWebACL"
      Rules: 
        - 
          Action: 
            Type: "ALLOW"
          Priority: 1
          RuleId: !Ref SPARule
          
Outputs:
  RuleID:
    Description: The Rule ID
    Value: !Ref SPARule

  IPSetLogicalID:
    Description: The Logical ID
    Value: !Ref SPAWAFIPSet

  WEBACLID:
    Description: The Logical ID
    Value: !Ref SPAWebACL