AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS WAF"

Parameters:
  SPAIPSetRule:
    Type: String
    Default: "SPAIPRule"
    Description: "Rule Name"

Resources:
  SAPRule:
    Type: "AWS::WAF::Rule"
    Properties: 
      MetricName: !Ref SPAIPSetRule
      Name: !Ref SPAIPSetRule
      Predicates:
      - 
        DataId: "ff8fef89-620a-4a75-9db3-ff8c8bf4035a"
        Negated: false
        Type: "IPMatch"
Outputs:
  RuleID:
    Description: The Rule ID
    Value: !Ref SAPRule