AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS WAF"
Resources:
  SPAWAF:
    Type: "AWS::WAF::IPSet"
    Properties: 
      Name: "IPSet for blacklisted IP adresses"
      IPSetDescriptors: 
        - 
          Type: "IPV4"
          Value: "192.0.2.44/32"
        - 
          Type: "IPV4"
          Value: "192.0.7.0/24"