AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS WAF"
Resources:
  SPAWAFIPSet:
    Type: "AWS::WAF::IPSet"
    Properties: 
      Name: "IPSet for blacklisted IP adresses"
      IPSetDescriptors: 
        - 
          Type: "IPV4"
          Value: "192.0.2.44/32"
        - 
          Type: "IPV4"
          Value: "192.0.7.0/24"
  SAPRule:
    Type: "AWS::WAF::Rule"
    Properties: 
      MetricName: !Ref AWS::StackName
      Name: !Ref AWS::StackName
      Predicates:
      - 
        DataId:
          Ref: "SPAWAFIPSet"
        Negated: false
        Type: "IPMatch"