AWSTemplateFormatVersion: 2010-09-09
Description: Build AWS CodeBuild

Parameters:
  ProjectName:
    Description: Project Name for CodeBuild
    Default: CodeBuild-saleforce
    Type: String

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
                - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: !Sub CodeBuildPolicy-${ProjectName}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents


  TestCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: salesforce batch
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: "NO_ARTIFACTS"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:2.7.12
      Source:
        Location: "https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/test-commit"
        Type: CODECOMMIT
      Tags:
        - Key: Name
          Value: !Ref ProjectName
