AWSTemplateFormatVersion: "2010-09-09"
Description: "Example APIGateWay IAM"
  StepFunctionsAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 