AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"
Parameters:
  SPABucketName:
    Type: String
    Description: Enter Bucket Name for SPA

  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
    Description: デプロイ対象のステージ名

Conditions:
  IsDevelopment: !Equals [ !Ref Env, dev ]

Resources:
  test:
    Condition: IsDevelopment
  test2:
    Condition: IsDevelopment