AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"
Parameters:
  SPABucketName:
    Type: String
    Default: NoValue
    Description: Enter Bucket Name for SPA

  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
    Description: デプロイ対象のステージ名

Conditions:
  IsDevelopment: !Equals [ !Ref Env, dev ]
  setBucketName: !Not [!Equals [!Ref SPABucketName , NoValue]]

Resources:
  S3Bucket:
    Condition: IsDevelopment
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
        Fn::If:
          - setBucketName
          - !Sub ${SPABucketName}
          - !Ref AWS::NoValue